services:
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=cgi_proov
      - POSTGRES_PASSWORD=prooviylesanne
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data